version: "3"
services:
  sls:
    build: .
    container_name: sls_template
    tty: true
    volumes:
      - .:/opt/app
    ports:
      - "3000:3000"
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_template
    ports:
      - "4566:4566"
    environment:
      - DEBUG=true
      - DEFAULT_REGION=ap-northeast-1
      - HOSTNAME=localstack
      - LOCALSTACK_HOSTNAME=localstack
      - DATA_DIR=${DATA_DIR- }
