version: "3"
services:
  sls:
    build: .
    container_name: sls_template
    tty: true
    volumes:
      - .:/opt/app
    ports:
      - "3000:3000"
    environment:
      - DEFAULT_REGION=ap-northeast-1
      - LOCALSTACK_HOST=localstack
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_template
    ports:
      - "4566:4566"
    environment:
      - DEBUG=true
      - DEFAULT_REGION=ap-northeast-1
      - HOSTNAME=localstack
      - LOCALSTACK_HOSTNAME=localstack
      - DATA_DIR=${DATA_DIR- }
  dynamodb_admin:
    image: aaronshaf/dynamodb-admin
    tty: true
    container_name: dynamodb_admin
    ports:
      - "8001:8001"
    depends_on:
      - localstack
    environment:
      DYNAMO_ENDPOINT: http://localstack:4566
      AWS_REGION: ap-northeast-1
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy