service: serverless-python
frameworkVersion: '3'

package:
  exclude:
    - node_modules/**
    - .dynamodb/**
    - .serverless/**
    - tests/**
    - .coverage
    - test/**
    - spec/**
    - docker-compose.yml
    - Dockerfile
    - package.json

resources:
  - ${file(conf/resources/dynamodb.yml)}

provider:
  name: aws
  region: ap-northeast-1
  runtime: python3.9
  timeout: 60 # in seconds
  stage: ${opt:stage, self:custom.defaultStage}
  environment: ${file(./conf/env/${self:provider.stage}.yml)}
  iamRoleStatements: ${file(conf/provider/iam.yml)}

plugins:
  - serverless-python-requirements
  - serverless-offline
  - serverless-prune-plugin
  - serverless-localstack

custom:
  defaultStage: local
  serverless-offline:
    port: 3000
    host: 0.0.0.0
  localstack:
    host: http://localstack
    edgePort: 4566
    region: ap-northeast-1
    stages:
      - local

functions:
  hello:
    handler: api.handler.hello
    events:
      - http:
          path: /hello
          method: get

  setup_dynamodb:
    handler: api.handler.setup_dynamodb

  get_secrets:
    handler: api.handler.get_secrets
